# Generated by Django 4.1.13 on 2024-03-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_event_registration_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
