# Generated by Django 4.1.13 on 2024-04-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_event_registration_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_logo',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='dir_logo',
            field=models.ImageField(blank=True, null=True, upload_to='directories/'),
        ),
    ]
