# Generated by Django 4.1.13 on 2024-04-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_event_event_logo_listing_dir_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='founder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
