# Generated by Django 4.1.13 on 2024-04-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_founder'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
